import { supabase } from './index'
/**
 * fetch all quizes generated by users from supabase
 * @returns
 */
export const listQuizJson = async (from: number, to: number) => {
  const { data, error, count } = await supabase
    .from('ai_quiz_generations')
    .select('*', { count: 'exact' })
    .neq('context_md', null)
    .range(from, to)
  if (error) {
    console.error('supabase service: ', error)
    throw error
  }
  return { data, count }
}
