import { supabase } from './index'
/**
 * fetch all quizes generated by users from supabase
 * @returns
 */
export const listQuizJson = async () => {
  const { data, error } = await supabase.from('ai_quiz_generations').select('*')
  if (error) {
    console.error('supabase service: ', error)
    throw error
  }
  return data
}
