<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { ref, shallowRef, watch } from 'vue'

import { generateQuiz } from './scripts/service'
import { getDuration } from './utils/timeduration'

import type { quizResponse } from './type/Type'

import HeaderLayout from './components/Layout/HeaderLayout.vue'
import QuizDisplay from './components/QuizDisplay.vue'
import QuizForm from './components/QuizForm.vue'
import QuizResult from './components/QuizResult.vue'
import ProgressBar from './components/ProgressBar.vue'

const { t, locale } = useI18n()
const answer = shallowRef<quizResponse | null>(null)
const loading = ref<boolean>(false)
const hasBeenTouched = ref<boolean>(false)
const userAnswers = ref<(number | null)[]>([])
const showUserAnswers = ref<boolean[]>([])
const isInvalidAnswer = ref<(boolean | undefined)[]>([])
const totalQuestion = ref<number>(0)
const quizWrapper = ref<InstanceType<typeof QuizDisplay> | null>(null)
const showReaderScreen = ref<boolean>(false)
const showResultQuiz = ref<boolean>(false)
const showQuizForm = ref<boolean>(true)
const showQuizDisplay = ref<boolean>(false)
const contexte = ref<string>('')
const quizTimeDuration = ref<number>(0)
const infosQuiz = ref<string>('')

const handleGenerateQuiz = async (payload: {
  question: string
  difficulty: 'Facile' | 'Moyen' | 'Difficile'
  numberQuestions: 5 | 10 | 15
  url: string
}) => {
  loading.value = true
  const quizDurationGeneration = Date.now()
  let messageKey = ''
  try {
    const {
      text,
      context,
      messageKey: serviceMessageKey,
    } = await generateQuiz(
      payload.question,
      payload.difficulty,
      payload.numberQuestions,
      locale.value,
      payload.url,
    )
    messageKey = serviceMessageKey
    if (text) {
      answer.value = <quizResponse>JSON.parse(text)
      console.warn('Quiz generated successfully sur: ', payload.question)
      showUserAnswers.value = answer.value.quiz_questions.map(() => false)
      isInvalidAnswer.value = answer.value.quiz_questions.map(() => undefined)
      userAnswers.value = answer.value.quiz_questions.map(() => null)
      hasBeenTouched.value = false
      totalQuestion.value = answer.value.quiz_questions.length
      showQuizForm.value = false
      showQuizDisplay.value = true
      infosQuiz.value = messageKey
      if (contexte.value) {
        contexte.value = context
      }

      if (quizWrapper.value) {
        quizWrapper.value?.setFocus()
      }
    } else {
      infosQuiz.value = messageKey
    }
  } catch (error) {
    console.error('Error generating quiz:', error)
    infosQuiz.value = messageKey
  } finally {
    loading.value = false
    quizTimeDuration.value = getDuration(quizDurationGeneration)
  }
}

watch(locale, () => {
  document.title = t('seo.title')
})

const handelUpdateScreen = (): void => {
  showReaderScreen.value = true
}

const handleAnswerSubmit = (): void => {
  showResultQuiz.value = true
  showQuizDisplay.value = false
}

const handleAnswerSelected = (indexQuestion: number, indexUserNewChoice: number) => {
  userAnswers.value[indexQuestion] = indexUserNewChoice
}

const handleNewQuiz = () => {
  showQuizForm.value = true
  showResultQuiz.value = false
}
</script>

<template>
  <progress-bar v-if="loading" :progress-type="false" />
  <header-layout @language-changed="handelUpdateScreen" />
  <main class="container" role="main">
    <p v-if="showReaderScreen" aria-live="polite" aria-atomic="true" class="visually-hidden">
      {{ t('common.language_changed_announcement') }}
    </p>
    <section>
      <quiz-result
        v-if="answer && showResultQuiz"
        :answer="answer"
        :userAnswers="userAnswers"
        @new-quiz="handleNewQuiz"
      />
    </section>
    <section>
      <p v-if="infosQuiz">{{ t(infosQuiz) }}</p>
      <quiz-display
        v-if="answer && showQuizDisplay"
        :answer="answer"
        :userAnswers="userAnswers"
        :duration="quizTimeDuration"
        @answer-selected="handleAnswerSelected"
        @answer-submit="handleAnswerSubmit"
        ref="quizWrapper"
      />
    </section>
    <section>
      <quiz-form v-if="showQuizForm" @user-question="handleGenerateQuiz" :loading="loading" />
    </section>
    <hr />
    <section class="">
      <details name="api" v-if="answer">
        <summary role="button" class="outline secondary">
          show the API generated for the quiz
        </summary>
        <pre><code> {{ answer }}</code></pre>
      </details>
      <details name="api" v-if="contexte">
        <summary role="button" class="outline secondary">
          show the markdown generated by Jina the quiz
        </summary>
        <pre><code> {{ contexte }}</code></pre>
      </details>
    </section>
  </main>
</template>

<style scoped>
.d-none {
  display: none;
}
.bloc {
  max-width: max-content;
}
</style>
